title: Python Project ![logo](https://mrfanning.github.io/MrFanning.github.io-PythonProject/PythonL.png).
google_analytics:
description: Math 10 
github:
  is_project_page: false

theme: jekyll-theme-cayman
